// Generated by LiveScript 1.3.1
(function(){
  var root, express, path, getsecret, bing_api_key, Bing, app, get_image_url_throttled, get_image_url;
  root = typeof exports != 'undefined' && exports !== null ? exports : this;
  express = require('express');
  path = require('path');
  getsecret = require('getsecret');
  bing_api_key = getsecret('bing_api_key');
  Bing = require('node-bing-api')({
    accKey: bing_api_key
  });
  app = express();
  app.set('port', process.env.PORT || 8080);
  app.use(express['static'](path.join(__dirname, '')));
  root.count = 0;
  root.waiting = [];
  get_image_url_throttled = function(query, callback){
    if (root.count < 1) {
      root.count += 1;
      return get_image_url(query, function(){
        root.count -= 1;
        if (root.waiting.length > 0) {
          get_image_url_throttled.apply(null, root.waiting.shift());
        }
        return callback.apply(this, arguments);
      });
    } else {
      return root.waiting.push(arguments);
    }
  };
  get_image_url = function(query, callback){
    return Bing.images(query, {}, function(error, res2, body){
      var x;
      return callback((function(){
        var i$, ref$, len$, results$ = [];
        for (i$ = 0, len$ = (ref$ = body.d.results).length; i$ < len$; ++i$) {
          x = ref$[i$];
          results$.push(x.MediaUrl);
        }
        return results$;
      }()));
    });
  };
  app.get('/image', function(req, res){
    return get_image_url(req.query.name, function(imgurl){
      return res.send(imgurl);
    });
  });
  app.listen(app.get('port'), '0.0.0.0');
}).call(this);
