// Generated by LiveScript 1.3.1
(function(){
  window.addEventListener('WebComponentsReady', function(e){
    return $('#speechrecognition')[0].onresults = function(candidates){
      var i$, len$, x, results$ = [];
      console.log(candidates);
      $('#searchresults').html('');
      for (i$ = 0, len$ = candidates.length; i$ < len$; ++i$) {
        x = candidates[i$];
        results$.push($('<search-result-item>').prop('query', x).appendTo('#searchresults'));
      }
      return results$;
    };
  });
}).call(this);
