// Generated by LiveScript 1.3.1
(function(){
  Polymer({
    is: 'keyboard-button',
    properties: {
      keytext: {
        type: String,
        value: 'a'
      },
      ishidden: {
        type: Boolean,
        value: false,
        observer: 'visibilityChanged'
      }
    },
    visibilityChanged: function(){
      if (this.ishidden) {
        return this.style.visibility = 'hidden';
      } else {
        return this.style.visibility = 'visible';
      }
    },
    handleClick: function(){
      console.log('clicked: ' + this.keytext);
      if (this.clickCallback != null) {
        return this.clickCallback();
      }
    },
    setClickCallback: function(callback){
      return this.clickCallback = callback;
    }
  });
}).call(this);
